### ISSUE TITLE
Classify job failures due to OOM as User Error

### ISSUE THREAD

**Issue by tpalashki** [vmware/versatile-data-kit#410]
**What is the feature request? What problem does it solve?**
Currently, if a data job execution exceeds the allowed memory quota, the pod of the execution is immediately killed by Kubernetes and restarted. Which in turn usually results in a similar failure. Ultimately (after 3 re-attempts), the Kubernetes job fails, which is currently interpreted as Platform Error.

**Suggested solution**
Change the logic that determines the error type to report these failures as User Error. One way to determine that a pod has been terminated due to OOM, is to describe it and check the LastState of the container:
```yaml
Containers:
    <name>:
    ...
    Last State:     Terminated
        Reason:       OOMKilled
        Exit Code:    137
        Started:      Mon, 18 Oct 2021 16:31:40 +0300
        Finished:     Mon, 18 Oct 2021 16:39:05 +0300
```

**Acceptance criteria**
Jobs executions that are terminated due to OOM are classified as User Error.
