### ISSUE TITLE
Able to specify different credentials for Data Jobs and VDK SDK docker registries through the Helm Chart

### ISSUE THREAD

**Issue by mivanov1988** [vmware/versatile-data-kit#678]
**What is the feature request? What problem does it solve?**
Control Service Helm Chart supports different docker registries for Data Jobs images (.Values.deploymentDockerRepository) and the VDK SDK (.Values.deploymentVdkDistributionImage.registry). However, if the VDK SDK registry is different than the Data Jobs one and it is a private docker registry we won't be able to specify different credentials for it. As a result, the Data Job Kubernetes Pod won't be able to pull the VDK SDK image.

**Suggested solution**
1. Add the ability to specify credenatils for VDK SDK through the Helm Chart 
```yaml
deploymentVdkDistributionImage:
  registry: registry.hub.docker.com/versatiledatakit
  repository: quickstart-vdk
  tag: "release"
  registryType: "generic"
  registryUsernameReadOnly: ""
  registryPasswordReadOnly: ""
```
2. Create an additional secret template for the VDK SDK registry and propagate it to the Control Service deployment
3. Add the ability of the Control Service to propagate the above secret to the Data Job template 

**Additional context**
We should be able to specify different credentials for Data Jobs and VDK SDK registries through the Helm Chart.
